# ccver 路径与外部依赖配置。所有值都允许调用方通过环境变量覆盖。

: "${CCVER_DATA_HOME:=${XDG_DATA_HOME:-$HOME/.local/share}}"
: "${CCVER_CACHE_HOME:=${XDG_CACHE_HOME:-$HOME/.cache}}"
: "${CCVER_VERSIONS_DIR:=$CCVER_DATA_HOME/claude/versions}"
: "${CCVER_BIN_LINK:=$HOME/.local/bin/claude}"
: "${CCVER_PIN_FILE:=$CCVER_DATA_HOME/ccver/pinned-version}"
: "${CCVER_LOCK_FILE:=$CCVER_DATA_HOME/ccver/install.lock}"
: "${CCVER_STAGING_DIR:=$CCVER_CACHE_HOME/claude/staging}"
: "${CCVER_DOWNLOADS_DIR:=$CCVER_CACHE_HOME/ccver/downloads}"
: "${CCVER_ASSEMBLY_DIR:=$CCVER_VERSIONS_DIR/.ccver-staging}"
: "${CCVER_VERSION_LOCKS_DIR:=$CCVER_DATA_HOME/ccver/version-locks}"
: "${CCVER_NODE_BIN:=$(command -v node 2>/dev/null)}"
: "${CCVER_DOWNLOAD_WORKERS:=2}"
: "${CCVER_CHUNK_SIZE:=16777216}"
: "${CCVER_REQUEST_TIMEOUT_MS:=120000}"
: "${CCVER_NPM_PACKAGE:=@anthropic-ai/claude-code}"
: "${CCVER_RELEASES_URL:=https://downloads.claude.ai/claude-code-releases}"
